/**
 * Commonly known professions for autocomplete when adding an expert.
 * Typing a prefix (e.g. "Horti") matches and suggests full roles (e.g. "Horticulturist").
 */
export const EXPERT_ROLE_SUGGESTIONS: string[] = [
  'CTO',
  'UX / Design Lead',
  'Lead Software Engineer',
  'Sales Growth Lead',
  'Customer Advocate',
  'Finance Ops Manager',
  'Horticulturist',
  'Regulatory Affairs',
  'Data Privacy Officer',
  'DevOps Lead',
  'Quality Assurance Lead',
  'Technical Writer',
  'Sustainability Officer',
  'Risk Manager',
  'HR / People Lead',
  'Operations Manager',
  'Supply Chain Expert',
  'Industry Analyst',
  'Legal Counsel',
  'IP Attorney',
  'Clinical Advisor',
  'Pharmacologist',
  'Agronomist',
  'Veterinarian',
  'Architect',
  'Civil Engineer',
  'Chemist',
  'Biostatistician',
  'Ethics Advisor',
  'Diversity & Inclusion Lead',
  'Accountant',
  'Auditor',
  'Brand Manager',
  'Chief of Staff',
  'Compliance Officer',
  'Data Scientist',
  'Economist',
  'Environmental Engineer',
  'Financial Analyst',
  'General Counsel',
  'Insurance Underwriter',
  'Logistics Manager',
  'Manufacturing Lead',
  'Medical Director',
  'Patent Attorney',
  'Procurement Manager',
  'Product Designer',
  'Project Manager',
  'Public Relations',
  'Quality Engineer',
  'Research Scientist',
  'Safety Officer',
  'Tax Advisor',
  'Training & Development',
  'Urban Planner',
];
